version: '3.7'

services:
    app:
        image: ghcr.io/day-mon/silly-zach:mair
        labels:
          traefik.enable: "true"
          traefik.http.routers.zach.rule: "Host(`howtowhipandnaenae.ninja`)"
          traefik.http.routers.zach.entrypoints: "https"
          traefik.http.routers.zach.loadbalancer.server.port: "80"


